INSERT INTO proveedores (nombre, cantidad) VALUES ('Carne', 18);
INSERT INTO proveedores (nombre, cantidad) VALUES ('Verduras', 52);
INSERT INTO proveedores (nombre, cantidad) VALUES ('Frutas', 51);

INSERT INTO productos(nombre, cantidad) VALUES ('Barritas para gato', 105);
INSERT INTO productos(nombre, cantidad) VALUES ('Bites de pescado', 105);
INSERT INTO productos(nombre, cantidad) VALUES ('Codorniz deshidratada', 105);
INSERT INTO productos(nombre, cantidad) VALUES ('Colita de cerdo', 105);
INSERT INTO productos(nombre, cantidad) VALUES ('Condimento natural', 105);
INSERT INTO productos(nombre, cantidad) VALUES ('Green tripe deshidratada', 105);
INSERT INTO productos(nombre, cantidad) VALUES ('Laminas de pulmon', 105);
INSERT INTO productos(nombre, cantidad) VALUES ('Oreja de cerdo', 105);
INSERT INTO productos(nombre, cantidad) VALUES ('Oreja de res', 105);
INSERT INTO productos(nombre, cantidad) VALUES ('Pata jumbo de cerdo', 105);
INSERT INTO productos(nombre, cantidad) VALUES ('Patitas de pollo', 105);
INSERT INTO productos(nombre, cantidad) VALUES ('Premios a granel de cerdo', 105);
INSERT INTO productos(nombre, cantidad) VALUES ('Premios a granel de pollo', 105);
INSERT INTO productos(nombre, cantidad) VALUES ('Premios a granel de corazon', 105);
INSERT INTO productos(nombre, cantidad) VALUES ('Premios a granel de higado', 105);
INSERT INTO productos(nombre, cantidad) VALUES ('Premios a granel de bazo', 105);
INSERT INTO productos(nombre, cantidad) VALUES ('Premios a granel de riñon', 105);
INSERT INTO productos(nombre, cantidad) VALUES ('Traquea de res', 105);